package alumnosGUI;


//import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
//import java.util.Iterator;
import javax.swing.JOptionPane;

import Alumnos.Alumno;


public class ListadoAlumnado extends javax.swing.JFrame {
 
    ArrayList<Alumno> alumnado = new ArrayList<>();
    int pos = 0;
    /**
     * Creates new form ListadoAlumnado
     */
    public ListadoAlumnado() {
        initComponents();
       // this.setLocationRelativeTo(null); esta es otra forma de centrar la ventana
        //lerFicheiro();
      lerFicheiro2();
      //los botones siguiente y anterior están con setEnabled a false al principio(ver Properties))
       if (!alumnado.isEmpty()) {
            mostrarDatosAlumno(pos);
            if (alumnado.size() > 1) {
                jButtonSeguinte.setEnabled(true);
            }
        }
       
    }


    
//    private boolean lerFicheiro() {
//        //de esta forma se guarda objeto a objeto en el arraylist
//        boolean correcto = true;
//        try (ObjectInputStream ficheiro = 
//                new ObjectInputStream(new FileInputStream("alumnos.dat"))){  
//            while (true) {
//                alumnado.add((Alumno)ficheiro.readObject());
//            }
//        }catch(EOFException e){
//            
//        } catch (ClassNotFoundException e) {
//            System.out.println("ERROR: No se encuentra la clase da serialización");
//            correcto = false;
//        } catch (IOException e) {
//            System.out.println("AVISO: Problemas de entrada/salida. "
//                    + "Puede que el fichero no exista.");
//            correcto = false;
//        }
//        return correcto;
//    }
//    
    
    private void lerFicheiro2(){
        //de esta forma se guarda de forma completa en el arraylist todos los alumnos
      
     try 
     {
         ObjectInputStream ficheiro = 
                new ObjectInputStream(new FileInputStream("alumnos.dat"));
     
          alumnado = (ArrayList <Alumno>)ficheiro.readObject();
     }
     catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null,"No se encuentra la clase de serialización");
     }
     catch (IOException e)
             {
              JOptionPane.showMessageDialog(null,"Problemas de E/S, puede que el fichero no exista. Se creará alumnos.dat");   
             //realmente no se crea aquí, aquí solo se da el aviso, al salir en el botón de Cerrar se hace
             //el FileOutputStream en serializar2() y es donde si no existe se crea, vacío o no...
             }
     
    
    }
    
//    private boolean serializar() {
//        //lo mismo que al leer, aquí se puede hacer uno a uno
//        boolean correcto = true;
//        try (ObjectOutputStream ficheiro = 
//                new ObjectOutputStream(new FileOutputStream("alumnos.dat"))){  
//            Iterator<Alumno> iterador = alumnado.iterator();
//            while(iterador.hasNext()){
//                Alumno alumno = iterador.next();
//                ficheiro.writeObject(alumno);
//            }
//        } catch (IOException e) {
//            System.out.println("ERROR: Problemas de entrada/salida");
//            correcto = false;
//        }
//        return correcto;
//    }
    private void serializar2()
    { // o más cómodamente el arraylist completo
        try (ObjectOutputStream ficheiro = 
                new ObjectOutputStream(new FileOutputStream("alumnos.dat",false))){ 
             ficheiro.writeObject(alumnado);
        }
        catch (IOException e) {
            JOptionPane.showMessageDialog(null,"Error, problemas de E/S");
        }
    
    }
        
  
    private void mostrarDatosAlumno(int posicion) {
     
        Alumno alumno = alumnado.get(posicion);
        jTextFieldNome.setText(alumno.nome);
        jTextFieldDNI.setText(alumno.dni);
        jTextFieldIdade.setText(Integer.toString(alumno.idade));
        jTextFieldCurso.setText(alumno.curso);
        jTextFieldNota.setText(Float.toString(alumno.nota));
        if (alumno.repite) {
            jRadioButtonRepiteS.setSelected(true);
        } else {
            jRadioButtonRepiteN.setSelected(true);
        }
    }
    
    private void borrarDatos() {
        jTextFieldNome.setText("");
        jTextFieldDNI.setText("");
        jTextFieldIdade.setText("");
        jTextFieldCurso.setText("");
        jTextFieldNota.setText("");
        buttonGroupRepite.clearSelection();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupRepite = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRadioButtonRepiteS = new javax.swing.JRadioButton();
        jRadioButtonRepiteN = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldDNI = new javax.swing.JTextField();
        jTextFieldNota = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldIdade = new javax.swing.JTextField();
        jTextFieldCurso = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButtonAnterior = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButtonSeguinte = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión alumnado");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(0, 51, 102));

        jLabel6.setBackground(new java.awt.Color(0, 204, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("ALUMNADO");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaxes/botonSair2.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));

        jLabel1.setText("NOMBRE");

        jLabel2.setText("DNI");

        jLabel3.setText("NOTA");

        jLabel4.setText("Repite");

        buttonGroupRepite.add(jRadioButtonRepiteS);
        jRadioButtonRepiteS.setText("Si");

        buttonGroupRepite.add(jRadioButtonRepiteN);
        jRadioButtonRepiteN.setText("No");

        jLabel5.setText("CURSO");

        jTextFieldNome.setEditable(false);

        jTextFieldDNI.setEditable(false);

        jTextFieldNota.setEditable(false);

        jLabel7.setText("EDAD");

        jTextFieldIdade.setEditable(false);

        jTextFieldCurso.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jRadioButtonRepiteS)
                        .addGap(27, 27, 27)
                        .addComponent(jRadioButtonRepiteN)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextFieldNota)
                    .addComponent(jTextFieldDNI)
                    .addComponent(jTextFieldIdade)
                    .addComponent(jTextFieldCurso)
                    .addComponent(jTextFieldNome))
                .addGap(17, 17, 17))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextFieldCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonRepiteN, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonRepiteS)
                    .addComponent(jLabel4))
                .addGap(15, 15, 15))
        );

        jButtonAnterior.setText("Anterior");
        jButtonAnterior.setEnabled(false);
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });

        jButtonNovo.setText("Nuevo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSeguinte.setText("Siguiente");
        jButtonSeguinte.setEnabled(false);
        jButtonSeguinte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeguinteActionPerformed(evt);
            }
        });

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButtonEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jButtonNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAnterior)
                .addGap(14, 14, 14)
                .addComponent(jButtonSeguinte)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonAnterior)
                    .addComponent(jButtonSeguinte)
                    .addComponent(jButtonEliminar))
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        NovoAlumno novoA = new NovoAlumno(this, true);
        novoA.setVisible(true); //asi iniciamos el dialog
      if (novoA.getAlumno() != null) {  // o bien añadimos aquí el alumno que viene de nuevo alumno
            alumnado.add(novoA.getAlumno());
        } // hasta aquí se añade el alumno o se hacía en NovoAlumno añadiendo ya el objeto en la lista
        if (!alumnado.isEmpty()) {
            mostrarDatosAlumno(pos);
            if (pos < alumnado.size()-1) {
                jButtonSeguinte.setEnabled(true);
            }
            jButtonEliminar.setEnabled(true);
        }
        
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        pos--;
        mostrarDatosAlumno(pos);
        if (pos < alumnado.size()-1) {
            jButtonSeguinte.setEnabled(true);
        }
        if (pos == 0) {
            jButtonAnterior.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonSeguinteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeguinteActionPerformed
        pos++;
        mostrarDatosAlumno(pos);
        jButtonAnterior.setEnabled(true);
        if (pos == alumnado.size()-1) {
            jButtonSeguinte.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonSeguinteActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        alumnado.remove(pos);
        if (alumnado.isEmpty()) {
            borrarDatos();
            jButtonEliminar.setEnabled(false);
            jButtonSeguinte.setEnabled(false);
            jButtonAnterior.setEnabled(false);
        } else {
            if (pos > 0) {
                pos--;
            }
            mostrarDatosAlumno(pos);
            if (alumnado.size() == 1) {
                jButtonAnterior.setEnabled(false);
                jButtonSeguinte.setEnabled(false);
            } else if (pos == 0) {
                jButtonAnterior.setEnabled(false);
                jButtonSeguinte.setEnabled(true);
            } else if (pos == alumnado.size()-1){
                jButtonAnterior.setEnabled(true);
                jButtonSeguinte.setEnabled(false);
            } else {
                jButtonAnterior.setEnabled(true);
                jButtonSeguinte.setEnabled(true);
            }          
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       // serializar();
        serializar2();
        //System.exit(0); asi cerramos o bien con dispose:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListadoAlumnado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListadoAlumnado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListadoAlumnado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListadoAlumnado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListadoAlumnado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupRepite;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonSeguinte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonRepiteN;
    private javax.swing.JRadioButton jRadioButtonRepiteS;
    private javax.swing.JTextField jTextFieldCurso;
    private javax.swing.JTextField jTextFieldDNI;
    private javax.swing.JTextField jTextFieldIdade;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNota;
    // End of variables declaration//GEN-END:variables
}
